### ISSUE TITLE
Javascript problem with pluggin

### ISSUE THREAD

**Issue by bhean** [blimey85/octopress-tapir#1]
Hi!
First, sorry for my english... 

I have a error after install this pluggin in the Javascript console:
TypeError: $(...).tapir is not a function

The problem is in this piece of code:

<script>
    $('#search_results').tapir({
        'token': 'my_tapir_token',
        'complete' : function() { document.getElementById('search_loading').style.display="none"; }
    });
</script>

I follow the installation instruction step by step and put my Tapir token, of course... 
Can you tell me something about that? It's a very useful pluggin, I really want to use it...

Thank you!!

**Comment by blimey85** [comment]
I'm sorry I didn't see this before now. Were you able to get it working?
